// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"img-xcx-tool/app/dao/internal"
)

// userImageDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userImageDao struct {
	*internal.UserImageDao
}

var (
	// UserImage is globally public accessible object for table user_image operations.
	UserImage userImageDao
)

func init() {
	UserImage = userImageDao{
		internal.NewUserImageDao(),
	}
}

// Fill with you ideas below.
