# HTTP Server
[server]
Address = ":6108"
#ServerRoot = "public"
ServerAgent = "jstgs-image-api"
LogPath = "/tmp/log/gf-app/jstgs-images"

# Logger.
[logger]
Path = "/tmp/log/jstgs-images"
Level = "all"
Stdout = true

# Template.
#[viewer]
#Path = "template"
#DefaultFile = "index.html"
#Delimiters = ["{{", "}}"]

# Database.
[database]
link = "mysql:root:root@tcp(127.0.0.1:3306)/jstgs_image"
debug = true
# Database logger.
[database.logger]
Path = "/tmp/log/gf-app/sql"
Level = "all"
Stdout = true
[gfcli]
[[gfcli.gen.dao]]
link = "mysql:root:root@tcp(127.0.0.1:3306)/jstgs_image"
tables = ""


[mini_program]
appid = "wx9d25bb982327bde5"
secret = "ac0e51349342520fbb4e168eb668f905"

[qiniu]
domain = "https://qiniu.storage.heifengni.com"
AccessKey = "_a84dBRWph1OoEYiGnFO7ZTJaFeHrf5ssjrCB4dT"
SecretKey = "LJ-oWZiEWFoixk09cQJUWu2CGRv-rtOwfkkYsUHk"
Bucket = "qiniu_storage"
Region = "https://up-z0.qiniup.com"
